<a href="https://colab.research.google.com/github/pushkarsonawane18/customers_shopping_data_tableau/blob/main/mcdy_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import kagglehub
path = kagglehub.dataset_download("nelgiriyewithana/mcdonalds-store-reviews")

Using Colab cache for faster access to the 'mcdonalds-store-reviews' dataset.

In [3]:
# Importing libraries
import pandas as pd
import numpy as np
import os
import re
import matplotlib.pyplot as plt

In [4]:
# listing directory path file name
os.listdir(path)

['McDonald_s_Reviews.csv']

In [5]:
file_path = os.path.join(path,'McDonald_s_Reviews.csv')

In [6]:
print(file_path)

/kaggle/input/mcdonalds-store-reviews/McDonald_s_Reviews.csv

In [7]:
# loading dataset

df = pd.read_csv(file_path, encoding='latin-1')

In [8]:
# shape
df.shape

(33396, 10)

In [9]:
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Why does it look like someone spit on my food?...,1 star
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,It'd McDonalds. It is what it is as far as the...,4 stars
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and che...,1 star
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...,5 stars
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,"I repeat my order 3 times in the drive thru, a...",1 star

In [10]:
df.dtypes

reviewer_id        int64
store_name        object
category          object
store_address     object
latitude         float64
longitude        float64
rating_count      object
review_time       object
review            object
rating            object
dtype: object

In [11]:
df['store_name'].value_counts()

store_name
McDonald's       33325
ýýýMcDonald's       71
Name: count, dtype: int64

In [12]:
df['category'].value_counts()

category
Fast food restaurant    33396
Name: count, dtype: int64

In [13]:
df['rating'].value_counts()

rating
5 stars    10274
1 star      9431
4 stars     5787
3 stars     4818
2 stars     3086
Name: count, dtype: int64

In [14]:
df.isnull().sum()

reviewer_id        0
store_name         0
category           0
store_address      0
latitude         660
longitude        660
rating_count       0
review_time        0
review             0
rating             0
dtype: int64

In [15]:
# Cleaning rating col

df['rating'] = df['rating'].str.replace(" stars","",regex=False)

In [16]:
df['rating'].value_counts()

rating
5         10274
1 star     9431
4          5787
3          4818
2          3086
Name: count, dtype: int64

In [17]:
# Cleaning rating col

df['rating'] = df['rating'].str.replace(" star","",regex=False)

In [18]:
df['rating'].value_counts()

rating
5    10274
1     9431
4     5787
3     4818
2     3086
Name: count, dtype: int64

In [19]:
# Cleaning Store name col

df['store_name'] = df['store_name'].str.replace(r"^[^a-zA-Z]+","",regex=True)

In [20]:
df['store_name'] = df['store_name'].str.replace("'","")

In [21]:
df['store_name'].value_counts()

store_name
McDonalds    33396
Name: count, dtype: int64

In [22]:
# clean rating count

df['rating_count'] = df['rating_count'].str.replace(',','')

In [23]:
df.shape

(33396, 10)

In [24]:
# Clean review col

df['review'].head(20)

0     Why does it look like someone spit on my food?...
1     It'd McDonalds. It is what it is as far as the...
2     Made a mobile order got to the speaker and che...
3     My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿...
4     I repeat my order 3 times in the drive thru, a...
5     I work for door dash and they locked us all ou...
6     If I  could give this location a zero on custo...
7     Came in and ordered a Large coffee w/no ice. T...
8     Went thru drive thru. Ordered. Getting home no...
9     I'm not really a huge fan of fast food, but I ...
10    Worst McDonaldï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿...
11    We stopped by for a quick breakfast.  It was n...
12    The morning crew seems fast and efficient. Nig...
13    Today, i was disappointed in that restaurant #...
14    Ordered food burger wrong and left out part of...
15    This was a dine in experience. The tables were...
16    The line wS extremely big and was moving very ...
17    The boy who attended me made me wait and when ...
18    I am not happy at all today I went and bought ...
19    The staff seems to always be different which m...
Name: review, dtype: object

In [25]:
special_chars = set()

for i in df['review'].dropna():
  found = re.findall(r'[^\x00-\x7f]',i)
  special_chars.update(found)

print(special_chars)

{'ï', '½', 'ý', '¿'}

In [26]:
df['review'] = df['review'].str.replace(r'[^\x00-\x7f]','',regex=True)

In [27]:
special_chars = set()

for i in df['review'].dropna():
  found = re.findall(r'[^\x00-\x7f]',i)
  special_chars.update(found)

print(special_chars)

set()

In [28]:
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,3 months ago,Why does it look like someone spit on my food?...,1
1,2,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,It'd McDonalds. It is what it is as far as the...,4
2,3,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,Made a mobile order got to the speaker and che...,1
3,4,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,a month ago,My mc. Crispy chicken sandwich was customer s...,5
4,5,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,2 months ago,"I repeat my order 3 times in the drive thru, a...",1

In [29]:
df.columns

Index(['reviewer_id', 'store_name', 'category', 'store_address', 'latitude ',
       'longitude', 'rating_count', 'review_time', 'review', 'rating'],
      dtype='object')

In [30]:
df.dtypes

reviewer_id        int64
store_name        object
category          object
store_address     object
latitude         float64
longitude        float64
rating_count      object
review_time       object
review            object
rating            object
dtype: object

In [31]:
df['rating'] = df['rating'].astype(int)

In [32]:
def label_sentiment(rating):
  if rating >= 4:
    return 'positive'
  elif rating == 3:
    return 'neutral'
  else:
    return 'negative'

In [33]:
df['sentiment'] = df['rating'].apply(label_sentiment)

In [34]:
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,sentiment
0,1,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,3 months ago,Why does it look like someone spit on my food?...,1,negative
1,2,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,It'd McDonalds. It is what it is as far as the...,4,positive
2,3,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,Made a mobile order got to the speaker and che...,1,negative
3,4,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,a month ago,My mc. Crispy chicken sandwich was customer s...,5,positive
4,5,McDonalds,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,2 months ago,"I repeat my order 3 times in the drive thru, a...",1,negative

In [35]:
df['sentiment'].value_counts()

sentiment
positive    16061
negative    12517
neutral      4818
Name: count, dtype: int64

# Text Preprocessing

In [36]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [37]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [38]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [39]:
stop_words = set(stopwords.words('english'))

In [40]:
import string

In [41]:
def text_preprocess(text):
  text = text.lower() # for lowercase
  text = text.translate(str.maketrans('','',string.punctuation)) # for punctuations
  tokens = word_tokenize(text) # for tokenize
  tokens = [t for t in tokens if t not in stop_words]
  return ' '.join(tokens)

In [42]:
df['cleaned_review'] = df['review'].dropna().apply(text_preprocess)

In [43]:
df['cleaned_review'].head()

0    look like someone spit food normal transaction...
1    itd mcdonalds far food atmosphere go staff mak...
2    made mobile order got speaker checked line mov...
3    mc crispy chicken sandwich customer service qu...
4    repeat order 3 times drive thru still manage m...
Name: cleaned_review, dtype: object

In [44]:
from nltk.stem import PorterStemmer # stemming
from nltk.stem import WordNetLemmatizer # lemmitization

In [45]:
stemmer = PorterStemmer()

In [46]:
lemmatizer = WordNetLemmatizer()

In [47]:
words = ['running','walking','cooking','happily','studying','reading','writing','sleeping','screaming','screening','streaming','dogs','cats']

In [50]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [51]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

True

In [52]:
print(lemmatizer.lemmatize('running', pos ='v'))

run

In [53]:
print("word   stemming    lemmitization")
print("-")
for word in words:
  print(f"{word:<11} {stemmer.stem(word):<11}  {lemmatizer.lemmatize(word)}")

word   stemming    lemmitization
-
running     run          running
walking     walk         walking
cooking     cook         cooking
happily     happili      happily
studying    studi        studying
reading     read         reading
writing     write        writing
sleeping    sleep        sleeping
screaming   scream       screaming
screening   screen       screening
streaming   stream       streaming
dogs        dog          dog
cats        cat          cat

In [61]:
df['store_name'] = df['store_name'].str.lower()

In [62]:
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,sentiment,cleaned_review
0,1,NaN,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,3 months ago,Why does it look like someone spit on my food?...,1,negative,look like someone spit food normal transaction...
1,2,NaN,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,It'd McDonalds. It is what it is as far as the...,4,positive,itd mcdonalds far food atmosphere go staff mak...
2,3,NaN,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,Made a mobile order got to the speaker and che...,1,negative,made mobile order got speaker checked line mov...
3,4,NaN,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,a month ago,My mc. Crispy chicken sandwich was customer s...,5,positive,mc crispy chicken sandwich customer service qu...
4,5,NaN,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,2 months ago,"I repeat my order 3 times in the drive thru, a...",1,negative,repeat order 3 times drive thru still manage m...

In [64]:
df['category'] = df['category'].str.lower()

In [66]:
df.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating,sentiment,cleaned_review
0,1,NaN,fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,3 months ago,Why does it look like someone spit on my food?...,1,negative,look like someone spit food normal transaction...
1,2,NaN,fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,It'd McDonalds. It is what it is as far as the...,4,positive,itd mcdonalds far food atmosphere go staff mak...
2,3,NaN,fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,5 days ago,Made a mobile order got to the speaker and che...,1,negative,made mobile order got speaker checked line mov...
3,4,NaN,fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,a month ago,My mc. Crispy chicken sandwich was customer s...,5,positive,mc crispy chicken sandwich customer service qu...
4,5,NaN,fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,1240,2 months ago,"I repeat my order 3 times in the drive thru, a...",1,negative,repeat order 3 times drive thru still manage m...

In [67]:
df.isnull().sum()

reviewer_id           0
store_name        33396
category              0
store_address         0
latitude            660
longitude           660
rating_count          0
review_time           0
review                0
rating                0
sentiment             0
cleaned_review        0
dtype: int64

In [68]:
df.shape

(33396, 12)